name: Block WIP merging
on:
  pull_request:
    types:
      - labeled
      - review_request_removed
      - review_requested
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted
  status:

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
      - name: Integration check
        uses: squalrus/merge-bot@v0.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: true
          labels: Feature ğŸ‰, Bug ğŸœ, Documentation ğŸ“’, Technical task ğŸ‘¨ğŸ»â€, Nice to have ğŸ¦
          blocking-labels: Work in progress ğŸš§
          checks_enabled: false
          checks: true
          method: squash
